use try-with-resource
eclipse-equinox/equinox pull request #262
Opened 2023-06-06 07:54 UTC by jukzi

2023-06-06 13:22 UTC, tjwatson reviewed
I've only looked at the `org.eclipse.osgi` changes so far.  I'll try to spend some time on the others.  But would be good if others could review because I am currently low on time I can focus here.

2023-06-06 19:15 UTC, HannesWell reviewed
I appricate this change and can have a look as well next week, when back from vacation.

2023-06-06 19:15 UTC, HannesWell commented on bundles/org.eclipse.equinox.common/src/org/eclipse/core/internal/boot/PlatformURLConnection.java
> +				while (count != -1) {
Can't we use Files.copy() here?
It accepts different combinations of streams and Paths.

2023-06-12 12:49 UTC, jukzi commented
Can equinox use BREE 17?
` The method transferTo(Writer) is undefined for the type Reader`

2023-06-12 13:26 UTC, jukzi commented
The bundle that shows an error is "org.eclipse.equinox.common".  Reader.transferTo(Writer) is defined in 9 and that bundle is already BREE 11. So it's an build error, that 8 is used to build! That can have negative consequences if removed methods are used.

2023-06-12 13:30 UTC, iloveeclipse commented
> The bundle that shows an error is "org.eclipse.equinox.common"

Are you sure?
```
[ERROR] Failed to execute goal org.eclipse.tycho:tycho-compiler-plugin:4.0.0-SNAPSHOT:compile (default-compile) on project org.eclipse.osgi: Compilation failure: Compilation failure: 
[ERROR] /home/jenkins/agent/workspace/equinox_PR-262/bundles/org.eclipse.osgi/container/src/org/eclipse/osgi/internal/log/EquinoxLogWriter.java:[375] 
[ERROR] 	fileIn.transferTo(this.writer);
[ERROR] 	       ^^^^^^^^^^
[ERROR] The method transferTo(Writer) is undefined for the type Reader
```

2023-06-12 13:33 UTC, jukzi commented
oh thanks, i used transferTo twice. EquinoxLogWriter is "org.eclipse.osgi". I'l revert for that package.

2023-06-21 00:12 UTC, HannesWell requested changes
Thanks for this PR (and your patience).
In general this looks good and this fixes a number of resource-leaks.

Just a few remarks for further improvements below.

Feel free to squash all code changes into one commit and the version bumps in another one.

2023-06-21 00:12 UTC, HannesWell commented on bundles/org.eclipse.osgi/container/src/org/eclipse/osgi/storage/Storage.java
> +					try (BufferedInputStream inStream = new BufferedInputStream(profileIn)) {
Same as above, another buffer is probably not necessary and `result.load(profileIn);` would probably be enough and even better.

2023-06-21 00:12 UTC, HannesWell commented on bundles/org.eclipse.osgi/container/src/org/eclipse/osgi/storage/Storage.java
> +	}
I think this is a good opportunity to add some braces :)
```suggestion
	private InputStream createProfileStream(Generation systemGeneration, String vmProfile, String embeddedProfileName) {
		InputStream profileIn = null;
		if (vmProfile != null) {
			// look for a profile in the system bundle based on the vm profile
			profileIn = findInSystemBundle(systemGeneration, vmProfile + PROFILE_EXT);
			if (profileIn == null) {
				profileIn = getNextBestProfile(systemGeneration, JAVASE, runtimeVersion, embeddedProfileName);
			}
		}
		if (profileIn == null) {
			// the profile url is still null then use the min profile the framework can use
			profileIn = findInSystemBundle(systemGeneration, "JavaSE-1.8.profile"); //$NON-NLS-1$
		}
		return profileIn;
	}
```

2023-06-21 00:12 UTC, HannesWell commented on bundles/org.eclipse.osgi/container/src/org/eclipse/osgi/storage/Storage.java
>  					result.load(new BufferedInputStream(profileIn));
I have the impression that Properties.load() already uses a buffer internally, therefore a BufferedInputStream would probably only add extra copying and GC work.
So result.load(profileIn); would probably be enough and even better.

2023-06-21 06:21 UTC, jukzi commented
i hope i incorporated all remarks.

2023-06-22 20:53 UTC, HannesWell approved these changes
> i hope i incorporated all remarks.

Looks good now. Thank you.

2023-06-22 20:56 UTC, merged