Continue without setting TCCL
eclipse-equinox/equinox pull request #447
Opened 2023-12-18 14:20 UTC by guw

When called from within a fork-join pool, setting the TCCL is not permitted. Therefore catch and continue without setting a TCCL.

Fixes #303.

2023-12-18 14:20 UTC, guw commented
@tjwatson Any guidance/requirements for unit testing this?

2024-04-16 14:49 UTC, tjwatson requested changes

2024-04-16 14:49 UTC, tjwatson commented on bundles/org.eclipse.osgi/container/src/org/eclipse/osgi/internal/framework/BundleContextImpl.java
> +			} catch (SecurityException e) {
I think we should catch `RuntimeException` here.  Given that the security manager deprecation/removal I look forward to the Java team wanting to throw some kind of `RuntimeException` here in the future instead.  I think that would be more safe, besides that, any reason for failing to set the TCCL here should not prevent the rest of the code flow.

2024-04-16 14:49 UTC, tjwatson commented on bundles/org.eclipse.osgi/container/src/org/eclipse/osgi/internal/framework/XMLParsingServiceFactory.java
> +				} catch (SecurityException e) {
Change to `RuntimeException`

2024-04-16 15:09 UTC, guw commented on bundles/org.eclipse.osgi/container/src/org/eclipse/osgi/internal/framework/BundleContextImpl.java
> +			} catch (SecurityException e) {
```suggestion
			} catch (RuntimeException e) {
```

2024-04-16 15:09 UTC, guw commented on bundles/org.eclipse.osgi/container/src/org/eclipse/osgi/internal/framework/XMLParsingServiceFactory.java
> +				} catch (SecurityException e) {
```suggestion
				} catch (RuntimeException e) {
```

2024-04-16 15:26 UTC, tjwatson approved these changes

2024-04-16 15:47 UTC, merged